POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "New event 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/1e1cfe4c-1230-4833-9c6a-4ab4a59f3056/attendees
Content-Type: application/json

{
  "name": "Letícia Mangueira",
  "email": "leticia22.mangueira@gmail.com"
}

###

GET http://localhost:3333/events/1e1cfe4c-1230-4833-9c6a-4ab4a59f3056

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/3/check-in

###

GET http://localhost:3333/events/1e1cfe4c-1230-4833-9c6a-4ab4a59f3056/attendees?query=letícia
